apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: mydeployment
    kind: frontend
spec:
  template:
    metadata:
      name: nginx-deploy
      labels:
        app: web
        type: frontend
    spec:
      containers:
        - name: nginx-deploy
          image: nginx:latest
          ports:
            - containerPort: 80
  replicas: 1
  selector:
    matchLabels:
      type: frontend