apiVersion: v1
kind: Pod
metadata: 
  name: multi-pod
  labels: 
    app: multi-pod
    type: network
spec: 
  containers:
    - name: nginx-alpine
      image: nginx:alpine
    - name: redis 
      image: redis
    - name: memcached 
      image: memcached